apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: goapp241204 
  janus-idp.io/tekton: goapp241204
  backstage.io/kubernetes-id: goapp241204
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: goapp241204
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  