apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: goapp241204
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goapp241204 
  name: goapp241204
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: goapp241204
    weight: 100 
