apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: goapp241204
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goapp241204 
  name: goapp241204
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: goapp241204 
