apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: goapp241204-gitops
  description: This is GitOps manifest for goapp241204   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: goapp241204
    janus-idp.io/tekton: goapp241204 
    backstage.io/kubernetes-id: goapp241204 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:goapp241204
